### ISSUE TITLE
Kobuki cannot be stopped properly

### ISSUE THREAD

**Issue by aksiksi** [hypower-org/jkobuki-2#2] opened 2015-05-07 17:34 UTC
OS: Windows 7 x86
JDK: 8u45

When I call k.stop(), two InterruptedException stack traces are printed. They are from KobukiRobot.java line 67 and SerialPortHandler.java line 95. For some odd reason, the threads are not cancelled and the call to baseControl in KobukiRobot.java line 81 is not completed.

So if the robot is moving and k.stop() is called, the robot does not stop and the program continues to run since the threads have not been cancelled.

I tried using receiveNB() in SerialPortHandler.java instead of receive(), but nothing changed. I'm not too sure what the problem is.

**Comment by drpjm** [comment] 2015-05-07 17:59
This is probably a bug with how the three scheduled tasks are shutdown. We will look over the logic. The stop() function should really be replaced by a safer sequence of steps.

**Comment by aksiksi** [comment] 2015-05-08 17:06
I've tried a few things to fix the issue, along with a lot of debugging. I tried interrupting the threads from the stop() method and removing the thread manager entirely. This didn't work. The issue is that the ExecutorService does not shutdown at all. This is very likely caused by a blocking task in either the SerialPortHandler or jssc itself. It's really difficult, for me at least, to pinpoint the exact cause.

More interestingly, even after the tasks are interrupted (checked using task.isCancelled()) and the ExecutorService continues to run, after some amount of time, the incoming queue becomes full and the VM runs out of heap memory! I have abolsutely no clue why such a memory leak would occur.

I actually have a competition next Saturday which involves the Kobuki. Do you think these issues will take long to fix? If so, should I work with the C++ kobuki_driver provided by the company? This library seems much easier to work with, not to mention the problem of memory management in C++ and the debugging overhead caused by it.

**Comment by drpjm** [comment] 2015-05-08 17:35
I do not think I would be able to get this code debugged and fixed by next week. I was planning to investigate it on Wednesday but then would not have a fix until the following week. I think the problem is going all the way down to the Serial port since it is IO and we do blocking calls on it. My plan is to somehow propagate a stop signal all the way down to the SPH, then close down the remaining tasks.

Do you need this stop functionality for the competition? This command is really meant to signal a full shutdown for the jkobuki, one reason we never tested it before. We usually run our code and when it is complete we just kill the program using it.

**Comment by aksiksi** [comment] 2015-05-08 17:40
Not really now that I think about it. I only need to stop it from moving.

**Comment by drpjm** [comment] 2015-05-08 17:42
Until I get this bug fixed, I would send baseControl(0,0) to stop your robot. stop() is really meant to perform a live, safe shutdown. My older library, jcreate (https://github.com/hypower-org/jcreate), performs such a shutdown correctly. I need to propagate this design into jkobuki.

I will keep this issue open.

**Comment by drpjm** [comment] 2015-05-12 12:41
Ok I just pushed a fix/full implementation of the KobukiRobot's requestShutdown() function. This method replaces stop().

**Closed as completed by drpjm** 2015-05-12 12:41 UTC
